# Generated by Django 2.1.8 on 2019-06-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmentation_type', models.CharField(choices=[('threshold', 'Threshold Segmentation'), ('mrf', 'Markov Random Field Segmentation'), ('kmeans', 'K-Means Segmenation')], max_length=30, verbose_name='Segmentation type')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('segmented_image', models.ImageField(upload_to='', verbose_name='Segmented Image')),
            ],
        ),
    ]
